DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
 id SERIAL PRIMARY KEY NOT NULL,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
 purchase_time TIMESTAMP NOT NULL,
 purchased BOOLEAN NOT NULL DEFAULT FALSE,
 removed BOOLEAN NOT NULL DEFAULT FALSE
);
