CREATE TABLE purchases (
 id SERIAL PRIMARY KEY NOT NULL,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 product_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 rating SMALLINT,
 message TEXT
);
