DROP TABLE IF EXISTS sessions CASCADE;

CREATE TABLE sessions (
 id SERIAL PRIMARY KEY NOT NULL,
 customer_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
 seller_id TEXT
);
