DROP TABLE IF EXISTS reviews CASCADE;

CREATE TABLE reviews (
 id SERIAL PRIMARY KEY NOT NULL,
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 product_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 rating SMALLINT NOT NULL,
 message TEXT
);
